### ISSUE TITLE
【robot.launch.pyで起動している限り問題なし】hardware.launch.pyでは、放電ボタンで放電実行できないOTL

### ISSUE THREAD

**Issue by Horie-Yuya** [SSL-Roots/FrootsPi#32]
hardware.launch.pyでは、放電ボタンで放電実行できない
robot.launch.pyでは、放電ボタンで放電実行できる
↓
原因判明
Kickerノードの一部メンバ変数の初期化を行っていなかったため、
放電ボタンを押しても、処理条件を入ることができなかった。OTL
↓
検証
コンストラクタでメンバ変数（charge_enable_from_conductor_）を初期化することで、放電ボタンで放電実行されることを確認
↓
対応
robot.launch.pyで起動している限り問題ないので、大会後修正（必要があれば、即時反映）

**Comment by ShotaAk** [comment]
380715be76b30475ac28e257627fbc41d2ede91c
で対応しました。
